backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "caseStudies"
    label: "Case Studies"
    folder: "content/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Hero Image", name: "hero", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
